### ISSUE TITLE
Kernel Panic on iPhone5,3 iOS 9.3.3

### ISSUE THREAD

**Issue by conorswee** [ganoninc/trident-kloader-updated#19]
Kernel Panics and reboots

**Comment by iTommy258** [comment]
I am not a developer at this project but it would recommend you, to post the crashlog from Settings -> Privacy -> Diagnostics -> Diagnostic Data -> "panic-....." and Post it to Pastebin that the Dev can help and look into it. I have a similar problem and can't fix because I am not an expert and stuff like that but when you need help on user level, feel free to ask me.

**Comment by Xernium** [comment]
For the 5,2 5,3 and the iPad 3,3 its broken atm. I'm sorry about this, we are already looking into it

**Comment by Xernium** [comment]
Closing this retroactively, its been fixed a while ago
