### ISSUE TITLE
Can it hurt my ipad mini (iPad2,5  P105AP  IOS 9.3.2)

### ISSUE THREAD

**Issue by deus187** [ganoninc/trident-kloader-updated#39]
Hi i got a ipad mini laying around here, 

my question is;
could i brick the device with the current tool or will the tool just not work??

otherwise who do i have to ask to add support for the device

**Comment by Xernium** [comment]
First up, this tool itself can't brick your iPad.  
With that said, we won't ever support this device and if we do support it one-day, it would be useless anyway because downgrading anything prior to iOS 10 requires Keys of the target firmware (because iOS 10 was the release to drop FW encryption).

So unless you find a way to come up with keys for that device you won't be able to downgrade, and until then adding support for the device is wasted time. Sorry.
