### ISSUE TITLE
trident updated to ipad 2.2 9.3.3

### ISSUE THREAD

**Issue by Danfrid** [ganoninc/trident-kloader-updated#4]
can U explain how can i downgrade to 6.1.3 or not?
thnks)

**Comment by ganoninc** [comment]
Your iPad is not supported yet. I'm see Monday if you can add offsets for your model.

**Comment by Danfrid** [comment]
![fovvqvbnsjs](https://cloud.githubusercontent.com/assets/4591705/21743665/d4f8af1c-d517-11e6-8884-c89debdb3bb7.jpg)

after i saw it, i compiled and installed for my device

but.. when i click yolo first time, my device reboot and i don't have root access or not(?)
and when click another time i saw w00t root

it's means nothing root? :c

**Comment by ganoninc** [comment]
I was wrong, I added your iPad yesterday to the original trident exploit ^^'

So I included in this project just now.

Clone the current version of trident-kloader-updated ;)

**Comment by Danfrid** [comment]
but what is means w00t root?

**Comment by mattargithub** [comment]
Can you send ipa link for ipad2 wifi  ios 9.3.4(13G35)
Model MC979HN/A

**Comment by Danfrid** [comment]
it will be useless
.ipa needs to be compiled using xcode.
I did so.
On the other hand, I do not know how..

**Comment by Xernium** [comment]
# Attention!
Not sure if this is of any help, but theres a compiled version of the project in the Builds folder: https://github.com/ganoninc/trident-kloader-updated/blob/master/build/Trident%2Bkloader%201.2.1.ipa  
To install it use cydia Impactor, which can be found here http://www.cydiaimpactor.com  

It works for both iPad 2 Wifi models, but!   

## On the iPad2,4 it's useless!  
There are no firmware keys for it  -> no bundles!  
Because of this, you cant downgrade this device!  

### The iPad2,1 Wifi model is fine on the other hand just download the iPA above and install it
